### ISSUE TITLE
新版docker缺少依赖

### ISSUE THREAD

**Issue by vbskycn** [Guovin/iptv-api#602]
![image](https://github.com/user-attachments/assets/481fae97-4757-4d1f-8132-e8bee2cae61f)

Starting periodic command scheduler: cron.
Traceback (most recent call last):
File "/tv-driver/main.py", line 5, in <module>
from utils.channel import (
File "/tv-driver/utils/channel.py", line 13, in <module>
from utils.speed import (
File "/tv-driver/utils/speed.py", line 9, in <module>
import yt_dlp
ModuleNotFoundError: No module named 'yt_dlp'
/tv_entrypoint.sh: line 15: gunicorn: command not found
Starting periodic command scheduler: cron.
Traceback (most recent call last):
File "/tv-driver/main.py", line 5, in <module>
from utils.channel import (
File "/tv-driver/utils/channel.py", line 13, in <module>
from utils.speed import (
File "/tv-driver/utils/speed.py", line 9, in <module>
import yt_dlp
ModuleNotFoundError: No module named 'yt_dlp'
/tv_entrypoint.sh: line 15: gunicorn: command not found
Starting periodic command scheduler: cron.
Traceback (most recent call last):
File "/tv-driver/main.py", line 5, in <module>
from utils.channel import (
File "/tv-driver/utils/channel.py", line 13, in <module>
from utils.speed import (
File "/tv-driver/utils/speed.py", line 9, in <module>
import yt_dlp
ModuleNotFoundError: No module named 'yt_dlp'
/tv_entrypoint.sh: line 15: gunicorn: command not found
Starting periodic command scheduler: cron.
Traceback (most recent call last):
File "/tv-driver/main.py", line 5, in <module>
from utils.channel import (
File "/tv-driver/utils/channel.py", line 13, in <module>
from utils.speed import (
File "/tv-driver/utils/speed.py", line 9, in <module>
import yt_dlp
ModuleNotFoundError: No module named 'yt_dlp'
/tv_entrypoint.sh: line 15: gunicorn: command not found
Starting periodic command scheduler: cron.
Traceback (most recent call last):
File "/tv-driver/main.py", line 5, in <module>
from utils.channel import (
File "/tv-driver/utils/channel.py", line 13, in <module>
from utils.speed import (
File "/tv-driver/utils/speed.py", line 9, in <module>
import yt_dlp
ModuleNotFoundError: No module named 'yt_dlp'
/tv_entrypoint.sh: line 15: gunicorn: command not found

**Comment by vbskycn** [comment]
找到问题了，docker也换了名字，已经搞好，关闭吧
