### ISSUE TITLE
工作流报错

### ISSUE THREAD

**Issue by KKL369** [Guovin/iptv-api#647]
### Occurrence environment

- [X] Workflow
- [ ] GUI
- [ ] Docker
- [ ] Command line

### Bug description

你好，昨天同步了最新代码，工作流报错

### Error log

```shell
2024-12-10T22:35:38.0254888Z Sorting: 100%|██████████| 789/789 [09:30<00:00,  1.36it/s]Traceback (most recent call last):
2024-12-10T22:35:38.0273105Z   File "/home/runner/work/iptv-api/iptv-api/main.py", line 214, in <module>
2024-12-10T22:35:38.0273939Z     loop.run_until_complete(update_source.start())
2024-12-10T22:35:38.0274487Z     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
2024-12-10T22:35:38.0275542Z   File "/opt/hostedtoolcache/Python/3.13.1/x64/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
2024-12-10T22:35:38.0276556Z     return future.result()
2024-12-10T22:35:38.0276941Z            ~~~~~~~~~~~~~^^
2024-12-10T22:35:38.0277567Z   File "/home/runner/work/iptv-api/iptv-api/main.py", line 200, in start
2024-12-10T22:35:38.0278224Z     await self.main()
2024-12-10T22:35:38.0278810Z   File "/home/runner/work/iptv-api/iptv-api/main.py", line 142, in main
2024-12-10T22:35:38.0279554Z     self.channel_data = await process_sort_channel_list(
2024-12-10T22:35:38.0280119Z                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-10T22:35:38.0280538Z     ...<3 lines>...
2024-12-10T22:35:38.0280822Z     )
2024-12-10T22:35:38.0281076Z     ^
2024-12-10T22:35:38.0281748Z   File "/home/runner/work/iptv-api/iptv-api/utils/channel.py", line 580, in process_sort_channel_list
2024-12-10T22:35:38.0282657Z     info_list = sort_urls_by_speed_and_resolution(name, info_list, logger)
2024-12-10T22:35:38.0283648Z   File "/home/runner/work/iptv-api/iptv-api/utils/speed.py", line 292, in sort_urls_by_speed_and_resolution
2024-12-10T22:35:38.0284802Z     filter_data.sort(key=combined_key, reverse=True)
2024-12-10T22:35:38.0285284Z     ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-10T22:35:38.0285995Z   File "/home/runner/work/iptv-api/iptv-api/utils/speed.py", line 282, in combined_key
2024-12-10T22:35:38.0286949Z     speed, delay, resolution, origin = item["speed"], item["delay"], item["resolution"], item["origin"]
2024-12-10T22:35:38.0287874Z                                        ~~~~^^^^^^^^^
2024-12-10T22:35:38.0288411Z TypeError: tuple indices must be integers or slices, not str
2024-12-10T22:35:41.1325472Z /home/runner/work/_temp/7db0fbc4-d834-4a74-8419-e0a30a09f9fe.sh: line 1:  1896 Segmentation fault      (core dumped) pipenv run dev
2024-12-10T22:35:41.1337289Z ##[error]Process completed with exit code 139.
2024-12-10T22:35:41.1420144Z Post job cleanup.
```

**Comment by Guovin** [comment]
更新代码，再试试

**Comment by KKL369** [comment]
> 更新代码，再试试

已无问题，谢谢作者辛勤付出
