### ISSUE TITLE
多次更新时提示测速日志文件被占用

### ISSUE THREAD

**Issue by Zhuazizizi** [Guovin/iptv-api#655]
### Don't skip these steps

- [X] I understand that I will be **blocked** if I *intentionally* remove or skip any mandatory\* field
- [X] I have checked through the search that there are no similar issues that already exist
- [X] I will not submit any issues that are not related to this project

### Occurrence environment

- [ ] Workflow
- [X] GUI
- [ ] Docker
- [ ] Command line

### Bug description

在1.5.5GUI版本，我更新一次节目列表后修改了下设置再更新的话就会提示[WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'output\\sort.log'并卡在这一步，看起来这应该是测速的结果日志文件？我必须 重启软件 或者 关闭测速排序选项 才可以重新更新节目。

还有个疑问是测速排序功能似乎只是检测了访问响应延迟排序，并没有实际的传输速度测试，经常会有一部分质量不行的（在同机器上用potplayer播放时能访问但速度在200-400k/s或更低，不足以流畅播放）混在其中，这功能能改进下增加实际的速度测试并排序吗，目前看来有点点不太实用，或者是我单纯的使用有误？

### Error log

```shell
Processing subscribe : 100%|███████████████████████████████████████████████████████████| 15/15 [04:04<00:00, 16.30s/it]
Update cancelled!ibe :  93%|███████████████████████████████████████████████████████    | 14/15 [01:18<00:13, 13.63s/it]
Processing subscribe : 100%|███████████████████████████████████████████████████████████| 15/15 [03:17<00:00, 13.19s/it]
湖南卫视: Hotel_fofa: 0, Subscribe: 316, total: 196████████████████████████████████████| 15/15 [03:17<00:00, 45.53s/it]
Checking if your network supports IPv6...
Your network supports IPv6
Total urls: 196, need to sort: 192
Sorting: 100%|███████████████████████████████████████████████████████████████████████| 192/192 [01:01<00:00,  2.61it/s]Exception in thread Thread-7 (run_loop):
Traceback (most recent call last):
  File "threading.py", line 1041, in _bootstrap_inner
  File "threading.py", line 992, in run
  File "tkinter_ui\tkinter_ui.py", line 119, in run_loop
  File "asyncio\base_events.py", line 721, in run_until_complete
  File "tkinter_ui\tkinter_ui.py", line 104, in run_update
  File "main.py", line 197, in start
  File "main.py", line 139, in main
  File "utils\channel.py", line 575, in process_sort_channel_list
  File "utils\tools.py", line 26, in get_logger
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'output\\sort.log'
```

**Comment by Guovin** [comment]
1.可能是日志写入进程没有被释放导致，我会修复该问题。
2.目前工作流已实现获取延迟和速率，其它工作方式待下版更新。

**Comment by Guovin** [comment]
v1.5.6已更新，该问题已修复。
